- hosts: routers
  vars_files:
    - group_vars/static_vars.yml
    - group_vars/dinamic_vars.yml
  gather_facts: false
  roles:
    - setup_capsman
- hosts: caps
  vars_files:
    - group_vars/static_vars.yml
    - group_vars/dinamic_vars.yml
  gather_facts: false
  roles:
    - setup_cap
