---
- name: WiFi settings
  community.routeros.command:
    commands:
# Настройка WiFi 2g
      - /interface wireless set [ find default-name=wlan1 ] band=2ghz-b/g/n channel-width=20/40mhz-XX disabled=no distance=indoors frequency={{frequency_2g}} installation=indoor mode=ap-bridge ssid={{wifi_name}} wireless-protocol=802.11
# Настройка WiFi 5g
      - /interface wireless set [ find default-name=wlan2 ] band=5ghz-a/n/ac channel-width=20/40/80mhz-XXXX disabled=no distance=indoors frequency={{frequency_5g}} installation=indoor mode=ap-bridge ssid={{wifi_name}} wireless-protocol=802.11
      - /interface wireless security-profiles set [ find default=yes ] authentication-types=wpa-psk,wpa2-psk mode=dynamic-keys supplicant-identity=MikroTik wpa2-pre-shared-key={{wifi_pass}} wpa-pre-shared-key={{wifi_pass}}